In [3]:

import pandas as pd
from scipy import stats
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
url1 = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_220903.txt"
url2 = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_220910.txt"
url3 = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_220917.txt"
url4 = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_220924.txt"
url5 = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_221001.txt"
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)
df4 = pd.read_csv(url4)
df5 = pd.read_csv(url5)

In [5]:
df = pd.concat([df1, df2, df3, df4, df5])

In [6]:
# get rid of extra strings in columns 
df.columns = df.columns.str.replace(" ", "")

In [7]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
count1 = df.count()[0]
df.describe()

             ENTRIES          EXITS
count    1057508.000    1057508.000
mean    41635383.067   33277237.344
std    219542836.244  192632065.919
min            0.000          0.000
25%       256918.750     146507.750
50%      1312754.500     905926.500
75%      5906965.500    3927866.000
max   2147261100.000 2122100296.000

In [8]:
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2022,00:00:00,REGULAR,7755369,2735692
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2022,04:00:00,REGULAR,7755375,2735700
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2022,08:00:00,REGULAR,7755385,2735729
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2022,12:00:00,REGULAR,7755434,2735792
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2022,16:00:00,REGULAR,7755526,2735831
...,...,...,...,...,...,...,...,...,...,...,...
211376,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/30/2022,05:00:00,REGULAR,0,804
211377,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/30/2022,09:00:00,REGULAR,0,804
211378,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/30/2022,13:00:00,REGULAR,0,804
211379,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/30/2022,17:00:00,REGULAR,0,804
211380,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,09/30/2022,21:00:00,REGULAR,0,804

In [15]:
len(df['STATION'].unique())

379

In [20]:
df2 = df.sort_values(by=['STATION','DATE','TIME'])

In [21]:
df2.head(50)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
33503,H007,R248,00-00-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,15825817,18930698
33548,H007,R248,00-00-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,61699432,39189422
33593,H007,R248,00-03-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,2299,16296
33638,H007,R248,00-03-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,2658570,1235214
33683,H007,R248,00-03-02,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,6754993,597149
33728,H007A,R248,02-00-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,84395,15301
33770,H007A,R248,02-00-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,93357,23104
33812,H007A,R248,02-00-02,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,62191,37628
33854,H007A,R248,02-00-03,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,53374,89275
33896,H007A,R248,02-00-04,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,34827,156889
33938,H007A,R248,02-01-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,3955,2
33980,H007A,R248,02-01-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,1,913
34022,H007A,R248,02-03-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,24673,480577
34064,H007A,R248,02-03-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,166075,1018028
34106,H007A,R248,02-03-02,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,257613,535597
34148,H007A,R248,02-03-03,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,343613,264837
34190,H007A,R248,02-03-04,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,146369,47036
34232,H007A,R248,02-05-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,395737,0
34274,H007A,R248,02-05-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,524311,277
34316,H008,R248,01-00-00,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,10639,300793
34358,H008,R248,01-00-01,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,29318,255852
34400,H008,R248,01-00-02,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,52950,138719
34442,H008,R248,01-00-03,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,424914,244384
34484,H008,R248,01-00-04,1 AV,L,BMT,08/27/2022,00:00:00,REGULAR,782754,114980
33504,H007,R248,00-00-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,15825825,18930866
33549,H007,R248,00-00-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,61699449,39189555
33594,H007,R248,00-03-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,2301,16333
33639,H007,R248,00-03-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,2658570,1235228
33684,H007,R248,00-03-02,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,6754996,597152
33729,H007A,R248,02-00-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,84433,15308
33771,H007A,R248,02-00-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,93373,23117
33813,H007A,R248,02-00-02,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,62203,37651
33855,H007A,R248,02-00-03,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,53381,89328
33897,H007A,R248,02-00-04,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,34830,157002
33939,H007A,R248,02-01-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,3955,2
33981,H007A,R248,02-01-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,1,913
34023,H007A,R248,02-03-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,24686,480702
34065,H007A,R248,02-03-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,166086,1018077
34107,H007A,R248,02-03-02,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,257620,535616
34149,H007A,R248,02-03-03,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,343630,264851
34191,H007A,R248,02-03-04,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,146392,47055
34233,H007A,R248,02-05-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,395737,0
34275,H007A,R248,02-05-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,524311,277
34317,H008,R248,01-00-00,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,10643,300865
34359,H008,R248,01-00-01,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,29323,255910
34401,H008,R248,01-00-02,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,52960,138756
34443,H008,R248,01-00-03,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,424928,244414
34485,H008,R248,01-00-04,1 AV,L,BMT,08/27/2022,04:00:00,REGULAR,782792,115008
33505,H007,R248,00-00-00,1 AV,L,BMT,08/27/2022,05:02:22,REGULAR,15825827,18930875
33550,H007,R248,00-00-01,1 AV,L,BMT,08/27/2022,05:02:22,REGULAR,61699450,39189561

In [23]:
df1.to_csv('fefe.csv')

In [40]:
data = pd.DataFrame(df1.groupby(['STATION','DATE','TIME']).sum())
data

                                ENTRIES  \
STATION   DATE       TIME
1 AV      08/27/2022 00:00:00  90432177
                     04:00:00  90432425
                     05:02:22  86941144
                     05:03:42  86941144
                     05:05:04  86941144
...                                 ...
ZEREGA AV 09/02/2022 05:00:00   3295539
                     09:00:00   3295936
                     13:00:00   3296120
                     17:00:00   3296368
                     21:00:00   3296497

                               EXITS
STATION   DATE       TIME
1 AV      08/27/2022 00:00:00                                           63692971
                     04:00:00                                           63693986
                     05:02:22                                           59969151
                     05:03:42                                           59969151
                     05:05:04                                           59969151
...                                                                          ...
ZEREGA AV 09/02/2022 05:00:00                                            2539837
                     09:00:00                                            2540072
                     13:00:00                                            2540308
                     17:00:00                                            2540693
                     21:00:00                                            2541128

[30103 rows x 2 columns]

In [46]:
data.to_csv('CSV.csv')

In [45]:
dif = data.diff()
dif.to_csv('dif.csv')